export default {
    controls: "locked",
    basalHeight: 10,
    fps: 60,
    enableFlying: true,
    skipIntro: false,
    skipCharacters: false,
    speedIntro: true,
    startTime: 12,
    movementSpeed: 0.5, //0.2
    daySpeed: 0.001,
    noSquare: false,
    fullscreen: false,
    noAnimations: false,
    noExtras: false,
    noTrees: false,
    noCharacters: false,
    production: true,
    videoHost: "http://assets.tzina.space/",
    //videoHost: null,
    platform: "desktop",
    skipLanding: false,
    skipInstructions: false,
    language: "eng"
}
