export default {
    controls: "locked",
    basalHeight: 10,
    fps: 60,
    enableFlying: true,
    skipIntro: true,
    startTime: 9,
    skipCharacters: true,
    movementSpeed: 0.5, //0.5
    skipCharacters: true,
    //movementSpeed: 1,
    daySpeed: 0.003,
    noSquare: false,
    fullscreen: false,
    noAnimations: true,
    noExtras: false,
    noTrees: true,
    noCharacters: true,
//    daySpeed: 0.08,
}
