export default {
    controls: "locked",
    basalHeight: 10,
    fps: 60,
    enableFlying: true,
    skipIntro: false,
    startTime: 9,
    skipCharacters: false,
    movementSpeed: 0.1, //0.5
    skipCharacters: false,
    //movementSpeed: 1,
    daySpeed: 0.003,
    noSquare: false,
    fullscreen: false,
    noAnimations: false,
    noExtras: false,
    noTrees: false,
    noCharacters: false,
//    daySpeed: 0.08,
}
